#  Created by PhuongTRAN on 20/08/20.
#  Copyright © 2020 PhuongTRAN. All rights reserved.

use_frameworks!

target 'Analytics Example' do
  #  Add path to Analytics project
  pod 'AicactusSDK'
end


